// Generated by https://quicktype.io

export interface IPhotosResponse {
  photos: IPhoto[];
}

export interface IPhoto {
  id: string;
  categoryId: number;
  src: string;
  likes: number;
  liked: boolean;
  userId: string;
}
